Learning NumPy

In [382]:
import numpy as np

In [383]:
x1 = (1, 2, 3, 4)
x2 = [5, 6, 7, 8]

In [384]:
numbers1 = np.array(x1)
numbers2 = np.array(x2)

In [385]:
numbers1

array([1, 2, 3, 4])

In [386]:
numbers2

array([5, 6, 7, 8])

In [387]:
x3 = [ [1, 2, 3, 4], [5, 6, 7, 8]]

In [388]:
array3 = np.array(x3)

In [389]:
array3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [390]:
array3.dtype

dtype('int32')

In [391]:
array3.ndim

2

In [392]:
array3.shape

(2, 4)

In [393]:
array3.size

8

In [394]:
array3.itemsize

4

In [395]:
for row in array3:
    print(row)

[1 2 3 4]
[5 6 7 8]


In [396]:
for row in array3:
    for column in row:
        print(column, end=" ")

1 2 3 4 5 6 7 8 

In [397]:
for i in array3.flat:
    print(i, end=" ")

1 2 3 4 5 6 7 8 

In [398]:
array3.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False