In [265]:
import numpy as np

In [266]:
x1 = (1, 2, 3, 4)
x2 = [5, 6, 7, 8]

In [267]:
numbers1 = np.array(x1)
numbers2 = np.array(x2)

In [268]:
numbers1

array([1, 2, 3, 4])

In [269]:
numbers2

array([5, 6, 7, 8])

In [270]:
x3 = [ [1, 2, 3, 4], [5, 6, 7, 8]]

In [271]:
array3 = np.array(x3)

In [272]:
array3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [273]:
array3.dtype

dtype('int32')

In [274]:
array3.ndim

2

In [275]:
array3.shape

(2, 4)

In [276]:
array3.size

8

In [277]:
array3.itemsize

4

In [278]:
for row in array3:
    print(row)

[1 2 3 4]
[5 6 7 8]


In [279]:
for row in array3:
    for column in row:
        print(column, end=" ")

1 2 3 4 5 6 7 8 