In [72]:
import numpy as np

In [73]:
x1 = (1, 2, 3, 4)
x2 = [5, 6, 7, 8]

In [74]:
numbers1 = np.array(x1)
numbers2 = np.array(x2)

In [75]:
numbers1

array([1, 2, 3, 4])

In [76]:
numbers2

array([5, 6, 7, 8])

In [77]:
x3 = [ [1, 2, 3, 4], [5, 6, 7, 8]]

In [78]:
array3 = np.array(x3)

In [79]:
array3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [80]:
x4 = [ [1, 2, 3.5, 4], [5, 6.5, 7, 8]]

In [81]:
array4 = np.array(x4)

In [82]:
array4

array([[1. , 2. , 3.5, 4. ],
       [5. , 6.5, 7. , 8. ]])