In [54]:
import numpy as np

In [55]:
x1 = (1, 2, 3, 4)
x2 = [5, 6, 7, 8]

In [56]:
numbers1 = np.array(x1)
numbers2 = np.array(x2)

In [57]:
numbers1

array([1, 2, 3, 4])

In [58]:
numbers2

array([5, 6, 7, 8])

In [59]:
x3 = [ [1, 2, 3, 4], [5, 6, 7, 8]]

In [60]:
np.array(x3)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [61]:
x4 = [ [1, 2, 3.5, 4], [5, 6.5, 7, 8]]

In [62]:
np.array(x4)

array([[1. , 2. , 3.5, 4. ],
       [5. , 6.5, 7. , 8. ]])