In [348]:
import numpy as np

In [349]:
x1 = (1, 2, 3, 4)
x2 = [5, 6, 7, 8]

In [350]:
numbers1 = np.array(x1)
numbers2 = np.array(x2)

In [351]:
numbers1

array([1, 2, 3, 4])

In [352]:
numbers2

array([5, 6, 7, 8])

In [353]:
x3 = [ [1, 2, 3, 4], [5, 6, 7, 8]]

In [354]:
array3 = np.array(x3)

In [355]:
array3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [356]:
array3.dtype

dtype('int32')

In [357]:
array3.ndim

2

In [358]:
array3.shape

(2, 4)

In [359]:
array3.size

8

In [360]:
array3.itemsize

4

In [361]:
for row in array3:
    print(row)

[1 2 3 4]
[5 6 7 8]


In [362]:
for row in array3:
    for column in row:
        print(column, end=" ")

1 2 3 4 5 6 7 8 

In [363]:
for i in array3.flat:
    print(i, end=" ")

1 2 3 4 5 6 7 8 

In [364]:
array3.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False