In [39]:
import numpy as np

In [40]:
x1 = (1, 2, 3, 4)
x2 = [5, 6, 7, 8]

In [41]:
numbers1 = np.array(x1)
numbers2 = np.array(x2)

In [42]:
numbers1

array([1, 2, 3, 4])

In [43]:
numbers2

array([5, 6, 7, 8])

In [44]:
x3 = [ [1, 2, 3, 4], [5, 6, 7, 8]]

In [45]:
np.array(x3)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])