### Basic Operations

In [2]:
import numpy as np

In [3]:
arr_1 = np.array([1, 2, 3])
arr_2 = np.array([4, 5, 6])

# Adition
print(arr_1 + arr_2)

# Subtraction
print(arr_1 - arr_2)

# Multiplication
print(arr_1 * arr_2)

# Division
print(arr_1 / arr_2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
