In [1]:
import numpy as np

### Indexing

In [ ]:
# Define a numpy array
arr = np.array([1,2,3,4,5])

# Access the first element
print(arr[0])
# or
print(arr[-5])
# Access the third element
print(arr[2])
# or
print(arr[-3])
# Access the last element
print(arr[4])
# or 
print(arr[-1])

1
1
3
3
5
5


In [19]:
# Define a 2D numpy array
arr_2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr_2d)

# Access the first element of the first row
print(arr_2d[0, 0])
# or
print(arr_2d[0,-3])
# or
print(arr_2d[-3, 0])
# or 
print(arr_2d[-3, -3])
print(85*"-")
# Access the third element of the second row 
print(arr_2d[1, 2])
# or
print(arr_2d[1,-1])
# or
print(arr_2d[-2, 2])
# or
print(arr_2d[-2, -1])
print(85*"-")
# Access the last element of the last row
print(arr_2d[2, 2])
# or
print(arr_2d[2,-1])
# or
print(arr_2d[-1, 2])
# or
print(arr_2d[-1, -1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
1
1
1
-------------------------------------------------------------------------------------
6
6
6
6
-------------------------------------------------------------------------------------
9
9
9
9
