In [1]:
import numpy as np

### Slicing

In [2]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# slicing from the index 1 to index 5
print(arr[1:6])

# slicing fromd the begining to index 4
print(arr[:5])

# slicing from 5 to the end of the array
print(arr[5:])

# slicing evry other element in the array
print(arr[::2])

[1 2 3 4 5]
[0 1 2 3 4]
[5 6 7 8 9]
[0 2 4 6 8]


In [ ]:
arr_2d = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]])
print(arr_2d)
print(85*"-")

# slicing first 2 rows and 3 columns
print(arr_2d[:2, 0:3])
print(85*"-")

# slicing all rows and the last two columns
print(arr_2d[:, -2:])


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
-------------------------------------------------------------------------------------
[[1 2 3]
 [6 7 8]]
-------------------------------------------------------------------------------------
[[ 4  5]
 [ 9 10]
 [14 15]]
