In [1]:
import numpy as np

### Creating a 1D array

In [2]:
arr_1d = np.array([1,2,3])
print(arr_1d)
print(f"Number od dimension: {arr_1d.ndim}")

[1 2 3]
Number od dimension: 1


### Creating a 2D array

In [5]:
arr_2d = np.array([[1,2,3],[4,5,6]])
print(arr_2d)
print(f"Number od dimension: {arr_2d.ndim}")

[[1 2 3]
 [4 5 6]]
Number od dimension: 2
