In [1]:
import numpy as np

### Slicing

In [2]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# slicing from the index 1 to index 5
print(arr[1:6])

# slicing fromd the begining to index 4
print(arr[:5])

# slicing from 5 to the end of the array
print(arr[5:])

# slicing evry other element in the array
print(arr[::2])

[1 2 3 4 5]
[0 1 2 3 4]
[5 6 7 8 9]
[0 2 4 6 8]
